export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const LOADING_DATA = "LOADING_DATA";
export const SET_DATA = "SET_DATA";
export const POST_DATA = "SET_DATA";
